
import java.awt.Color;
import javax.swing.JOptionPane;
import teste.atri;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Caio
 */
public class cadastro extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
        bt_cadastrar.setBackground(Color.blue);
    }
    /**
     *
     * @return
     */

    String usuario;
    String tipo;
    String email;
    String cpf;
    String senha;
    atri at = new atri();

    public boolean verifyFields() {
        usuario = txt_usuario.getText();
        email = txt_email.getText();
        cpf = txt_cpf.getText();
        senha = String.valueOf(txt_senha.getPassword());
        tipo = String.valueOf(caixa_hierarquia.getSelectedItem());

        // check empty fields
        if (usuario.trim().equals("") || email.trim().equals("") || cpf.trim().equals("") || senha.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Um ou mais campos estão vazios", "Campos Vazios", 2);
            return false;
        } else if (usuario.equals(at.getUsuario()) || email.equals(atri.getEmail()) || cpf.equals(atri.getCpf())) {
            JOptionPane.showMessageDialog(null, "Usuário, email ou CPF informados já foram cadastrados!", "Erro", 2);
            return false;
        } else if (!Validador.cpf(cpf)) {
            JOptionPane.showMessageDialog(null, cpf+ "CPF Informado valido!", "Erro", 2);
        } else {
            
            at.setUsuario(usuario);
            at.setSenha(senha);
            atri.setTipo(tipo);
            atri.setCpf(cpf);
            atri.setEmail(email);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Cadastro", 1);
            frame2 tela4 = new frame2();
            tela4.setLocationRelativeTo(null);
            tela4.setVisible(true);
            this.dispose();
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_cadastro = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_cpf = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###.###.###-##");
            txt_cpf = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        lbl_senha = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        lbl_voltarCadastro = new javax.swing.JLabel();
        lbl_tipoUsuario = new javax.swing.JLabel();
        caixa_hierarquia = new javax.swing.JComboBox<>();
        bt_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Balanço Geral de Mercadoria");
        setPreferredSize(new java.awt.Dimension(605, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(null);

        lbl_cadastro.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lbl_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cadastro.setText("Insira seus dados:");
        jPanel1.add(lbl_cadastro);
        lbl_cadastro.setBounds(20, 10, 400, 50);

        lbl_usuario.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("Nome de Usuário:");
        jPanel1.add(lbl_usuario);
        lbl_usuario.setBounds(20, 50, 350, 60);
        jPanel1.add(txt_usuario);
        txt_usuario.setBounds(20, 110, 500, 25);

        lbl_email.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setText("Email:");
        jPanel1.add(lbl_email);
        lbl_email.setBounds(20, 140, 180, 50);
        jPanel1.add(txt_email);
        txt_email.setBounds(20, 180, 500, 25);

        lbl_cpf.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_cpf.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cpf.setText("CPF:");
        jPanel1.add(lbl_cpf);
        lbl_cpf.setBounds(20, 210, 180, 50);
        jPanel1.add(txt_cpf);
        txt_cpf.setBounds(20, 260, 500, 25);

        lbl_senha.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("Senha:");
        jPanel1.add(lbl_senha);
        lbl_senha.setBounds(20, 290, 180, 50);

        txt_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_senha);
        txt_senha.setBounds(20, 340, 500, 25);

        lbl_voltarCadastro.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lbl_voltarCadastro.setForeground(new java.awt.Color(0, 153, 255));
        lbl_voltarCadastro.setText("Já possui uma conta? Clique Aqui!");
        lbl_voltarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_voltarCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_voltarCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_voltarCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_voltarCadastroMouseExited(evt);
            }
        });
        jPanel1.add(lbl_voltarCadastro);
        lbl_voltarCadastro.setBounds(20, 420, 350, 30);

        lbl_tipoUsuario.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_tipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipoUsuario.setText("Cadastrar como:");
        jPanel1.add(lbl_tipoUsuario);
        lbl_tipoUsuario.setBounds(20, 380, 190, 30);

        caixa_hierarquia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuário" }));
        jPanel1.add(caixa_hierarquia);
        caixa_hierarquia.setBounds(210, 380, 120, 30);

        bt_cadastrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bt_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        bt_cadastrar.setText("CADASTRAR");
        bt_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cadastrar);
        bt_cadastrar.setBounds(150, 460, 290, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaActionPerformed

    private void lbl_voltarCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_voltarCadastroMouseEntered
        lbl_voltarCadastro.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbl_voltarCadastroMouseEntered

    private void lbl_voltarCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_voltarCadastroMouseExited
        lbl_voltarCadastro.setForeground(Color.blue);
    }//GEN-LAST:event_lbl_voltarCadastroMouseExited

    private void lbl_voltarCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_voltarCadastroMouseClicked
        frame2 tela4 = new frame2();
        tela4.setLocationRelativeTo(null);
        tela4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_voltarCadastroMouseClicked

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        verifyFields();
        at.salvar();
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JComboBox<String> caixa_hierarquia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cadastro;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_tipoUsuario;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JLabel lbl_voltarCadastro;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
